# Generated by Django 5.0.6 on 2024-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descripcio', models.CharField(max_length=500)),
            ],
        ),
    ]
